
path: C:/Users/taylo/Documents/VSCODE/yolo/data  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/train  # val images (relative to 'path')

nc: 1                # number of classes (1 for wallet)
# Classes
names:
  0: wallet
